$(".logo").click(()=>{
    document.location.href="index.html";
})
$('.dashboard').click(()=>{
    document.location.href="index.html";
})
$('.dashboard2').click(()=>{
    document.location.href="dashboard2.html";
})
$('.carouselE').click(()=>{
    document.location.href="carousel.html";
})
$('.social').click(()=>{
    document.location.href="social.html";
})
